import {loadScores,saveScore,scoreError} from './scores.js';
const $=id=>document.getElementById(id),ctx=$('board').getContext('2d');
let sdk,user,snake,food,dir,next,score=0,running=false,paused=false,timer,session,saving=false,finished=false;
function draw(){ctx.fillStyle='#07101c';ctx.fillRect(0,0,400,400);if(!snake)return;ctx.fillStyle='#ff6f91';if(food)ctx.fillRect(food.x*20+3,food.y*20+3,14,14);snake.forEach((cell,i)=>{ctx.fillStyle=i?'#4ade80':'#a7f3d0';ctx.fillRect(cell.x*20+1,cell.y*20+1,18,18)});}
function placeFood(){const free=[];for(let y=0;y<20;y++)for(let x=0;x<20;x++)if(!snake.some(c=>c.x===x&&c.y===y))free.push({x,y});food=free[Math.floor(Math.random()*free.length)]||null;}
function steer(key){const vectors={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}};const v=vectors[key];if(running&&!paused&&v&&!(v.x===-dir.x&&v.y===-dir.y))next=v;}
function schedule(){timer=setTimeout(step,Math.max(80,230-Math.floor(score/3)*15));}
function step(){if(!running||paused)return;dir=next;const h={x:snake[0].x+dir.x,y:snake[0].y+dir.y},eat=food&&h.x===food.x&&h.y===food.y;const body=eat?snake:snake.slice(0,-1);if(h.x<0||h.y<0||h.x>=20||h.y>=20||body.some(c=>c.x===h.x&&c.y===h.y)){end();return;}snake.unshift(h);if(eat){score++;$('score').textContent=score;$('level').textContent='Level '+(1+Math.floor(score/3));placeFood();if(!food){draw();end();return;}}else snake.pop();draw();schedule();}
async function persist(){if(saving)return;saving=true;$('start').disabled=true;$('retry').hidden=true;$('status').textContent='Game over · Score '+score+' · Saving…';try{await saveScore(session,score);$('status').textContent=user.displayName+' · Score '+score+' saved.';}catch(e){$('status').textContent='Score '+score+' was not confirmed saved. '+scoreError(e);$('retry').hidden=false;}finally{saving=false;$('start').disabled=!$('retry').hidden;}}
function end(){running=false;finished=true;clearTimeout(timer);$('pause').disabled=true;persist();}
$('start').onclick=()=>{if(!user||saving||!$('retry').hidden)return;session=crypto.randomUUID();finished=false;score=0;snake=[{x:8,y:10},{x:7,y:10},{x:6,y:10}];dir=next={x:1,y:0};paused=false;running=true;$('score').textContent='0';$('level').textContent='Level 1';$('start').disabled=true;$('pause').disabled=false;$('pause').textContent='Pause';$('status').textContent='Playing as '+user.displayName;placeFood();draw();schedule();};
$('pause').onclick=()=>{if(!running)return;paused=!paused;$('pause').textContent=paused?'Resume':'Pause';$('status').textContent=paused?'Paused':'Playing as '+user.displayName;clearTimeout(timer);if(!paused)schedule();};
$('retry').onclick=persist;document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>steer(b.dataset.dir));
window.addEventListener('keydown',e=>{if(e.target.matches('input,button'))return;const keys={ArrowUp:'up',w:'up',ArrowDown:'down',s:'down',ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right'};if(keys[e.key]){e.preventDefault();steer(keys[e.key]);}if(e.code==='Space'){e.preventDefault();$('pause').click();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&running&&!paused)$('pause').click();});
window.addEventListener('beforeunload',e=>{if(running||saving||finished&&!$('retry').hidden){e.preventDefault();e.returnValue='';}});
$('name-form').onsubmit=async e=>{e.preventDefault();const name=$('player-name').value.trim();if(!name)return;try{await sdk.updateProfile(user,{displayName:name});await user.getIdToken(true);$('name-form').hidden=true;$('player').textContent='Player: '+name;$('start').disabled=false;$('status').textContent='Press Play to begin.';}catch(e){$('status').textContent='Could not save your name. Please retry.';}};
draw();loadScores().then(s=>{sdk=s;user=s.auth.currentUser;if(!user){location.replace('login.html');return;}s.onAuthStateChanged(s.auth,u=>{if(!u){clearTimeout(timer);running=false;location.replace('login.html');}});if(!user.displayName?.trim()){$('name-form').hidden=false;$('status').textContent='Add your name before playing.';return;}$('player').textContent='Player: '+user.displayName;$('start').disabled=false;$('status').textContent='Press Play to begin.';}).catch(e=>{$('status').textContent=scoreError(e);});
